[tool.black]
line-length = 99
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''

[tool.pyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__"]
ignore = []

stubPath = "src/stubs"
venvPath = ".venv"

reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownVariableType = false

pythonVersion = "3.11"
typeCheckingMode = "strict"

executionEnvironments = [
  { root = "./", pythonVersion = "3.11", extraPaths = ["src"] }
]

# [tool.pytest]
# junit_family: xunit2

[tool.mypy]
# plugins = sqlmypy
python_version = 3.11

# flake8-mypy expects the two following for sensible formatting
show_column_numbers = true

# show error messages from unrelated files
follow_imports = "normal"

# suppress errors about unsatisfied imports
ignore_missing_imports = true

# be strict
disallow_untyped_calls = false
warn_return_any=true
strict_optional=true
warn_no_return=true
warn_redundant_casts=true
warn_unused_ignores=true
disallow_any_generics=true

# The following are off by default.  Flip them on if you feel
# adventurous.
disallow_untyped_defs=true
check_untyped_defs=true

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=99
known_third_party ="_pytest, pytest"

[tool.pydocstyle]
inherit = false
ignore ="D100, D101, D102, D103, D104, D105, D106, D107, D203, D204, D213, D215, D400, D401, D404, D406, D407, D408, D409, D413"

[tool.pytest.ini_options]
junit_family = "xunit2"
testpaths = ["tests",]
filterwarnings = ["ignore::DeprecationWarning",]
